# Generated by Django 5.1.1 on 2024-11-06 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0002_menuitem_catagory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catagory",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="menuitem",
            old_name="catagory",
            new_name="category",
        ),
    ]
